const mySkills = [
  {
    id: 1,
    name: "Hyper Text Machine Language",
    shortName: "HTML",
    procent: 85,
    image: "../images/icons/html-icon.png",
    color: "#f06529",
  },
  {
    id: 2,
    name: "Cascading Style Sheets",
    shortName: "Css",
    procent: 70,
    image: "../images/icons/css-icon.png",
    color: "#2965f1",
  },
  {
    id: 3,
    name: "Sassy Cascading Style Sheets",
    shortName: "SCSS",
    procent: 70,
    image: "../images/icons/sass-icon.png",
    color: "#cc6699",
  },
  {
    id: 4,
    name: "JavaScript",
    shortName: "JS",
    procent: 60,
    image: "../images/icons/javascript-icon.png",
    color: "#f0db4f",
  },
  {
    id: 5,
    name: "TypeScript",
    shortName: "TS",
    procent: 55,
    image: "../images/icons/typescript-icon.png",
    color: "#3178c6",
  },
  {
    id: 6,
    name: "ReactJs",
    shortName: "React",
    procent: 60,
    image: "../images/icons/react-icon.png",
    color: "#00d8ff",
  },
  {
    id: 8,
    name: "NextJs",
    shortName: "Next",
    procent: 45,
    image: "../images/icons/next-icon.png",
    color: "#000",
  },
  {
    id: 9,
    name: "Bootstrap",
    shortName: "BS",
    procent: 75,
    image: "../images/icons/bootstrap-icon.png",
    color: "#563d7c",
  },
  {
    id: 10,
    name: "Tailwind",
    shortName: "TW",
    procent: 55,
    image: "../images/icons/tailwind-icon.png",
    color: "#06b6d4",
  },
];
const myWorks = [
  {
    id: 1,
    name: "Gilam Saray",
    url: "https://gilamsaray.uz/",
    image: "../images/gilamsaray.png",
    gurl: "https://github.com/AzizbekGitHub99/gilam-saray",
    backend: false,
  },
  {
    id: 2,
    name: "InHouse",
    url: "https://inhouse-getter.netlify.app/",
    image: "../images/inhouse.png",
    gurl: "https://github.com/AzizbekGitHub99/inhouse-GETTER",
    backend: true,
  },
  {
    id: 3,
    name: "Shaxmat Federatsiyasi",
    url: "https://shaxmat-federatsiyasi.netlify.app/",
    image: "../images/shaxmat.png",
    gurl: "https://github.com/AzizbekGitHub99/shaxmat-GETTER",
    backend: true,
  },
  {
    id: 4,
    name: "Sultan e-Market",
    url: "https://sultan-clone.netlify.app/",
    image: "../images/sultan.jpg",
    gurl: "https://github.com/AzizbekGitHub99/SultanOnlineMarket",
    backend: true,
  },
  {
    id: 5,
    name: "CRUD - MOCK",
    url: "https://crudwithmock.netlify.app/",
    image: "../images/crud-mock.png",
    gurl: "https://github.com/AzizbekGitHub99/CRUDwithmock",
    backend: true,
  },
  {
    id: 6,
    name: "Kuda Pizza",
    url: "https://kudapizzafromazyzbe.netlify.app/",
    image: "../images/kuda-pizza.png",
    gurl: "https://github.com/AzizbekGitHub99/kudapizza",
    backend: true,
  },
  {
    id: 7,
    name: "Full ToDo App",
    url: "https://fulltodoapp.netlify.app/",
    image: "../images/todo.png",
    gurl: "https://github.com/AzizbekGitHub99/fulltodoapp",
    backend: true,
  },
  {
    id: 8,
    name: "Serveryanochka",
    url: "https://azyzbeexam.netlify.app/",
    image: "../images/serveryanochka.png",
    gurl: "https://github.com/AzizbekGitHub99/Exam-4",
    backend: true,
  },
  {
    id: 9,
    name: "Countries",
    url: "https://countriefromazyzbe.netlify.app/",
    image: "../images/countries.png",
    gurl: "https://github.com/AzizbekGitHub99/Countries",
    backend: true,
  },
  {
    id: 10,
    name: "Phone (Click Power on)",
    url: "https://phonefromazyzbe.netlify.app/",
    image: "../images/phone.png",
    gurl: "https://github.com/AzizbekGitHub99/Phone",
    backend: true,
  },
  {
    id: 11,
    name: "Pokemon",
    url: "https://pokemonsfromazyzbe.netlify.app/",
    image: "../images/pokemon.png",
    gurl: "https://github.com/AzizbekGitHub99/pokemonfromazyzbe",
    backend: true,
  },
  {
    id: 12,
    name: "Drag and Drop",
    url: "https://draganddropfromazizbe.netlify.app/",
    image: "../images/dnd.png",
    gurl: "https://github.com/AzizbekGitHub99/test-dnd",
    backend: true,
  },
  {
    id: 13,
    name: "Weather App",
    url: "https://weatherappfromazizbe.netlify.app/",
    image: "../images/weather.jpg",
    gurl: "https://github.com/AzizbekGitHub99/weather-app",
    backend: true,
  },
  {
    id: 14,
    name: "Blog App",
    url: "http://azizbek-dev.uz/",
    image: "../images/blog.png",
    gurl: "https://github.com/AzizbekGitHub99/blogwebsite",
    backend: false,
  },
];

export { mySkills, myWorks };
