const mySkills = [
  {
    id: 1,
    name: "Hyper Text Machine Language",
    shortName: "HTML",
    procent: 85,
    image: "../images/icons/html-icon.png",
    color: "#f06529",
  },
  {
    id: 2,
    name: "Cascading Style Sheets",
    shortName: "Css",
    procent: 70,
    image: "../images/icons/css-icon.png",
    color: "#2965f1",
  },
  {
    id: 3,
    name: "Sassy Cascading Style Sheets",
    shortName: "SCSS",
    procent: 70,
    image: "../images/icons/sass-icon.png",
    color: "#cc6699",
  },
  {
    id: 4,
    name: "JavaScript",
    shortName: "JS",
    procent: 60,
    image: "../images/icons/javascript-icon.png",
    color: "#f0db4f",
  },
  {
    id: 5,
    name: "TypeScript",
    shortName: "TS",
    procent: 55,
    image: "../images/icons/typescript-icon.png",
    color: "#3178c6",
  },
  {
    id: 6,
    name: "ReactJs",
    shortName: "React",
    procent: 60,
    image: "../images/icons/react-icon.png",
    color: "#00d8ff",
  },
  {
    id: 8,
    name: "NextJs",
    shortName: "Next",
    procent: 45,
    image: "../images/icons/next-icon.png",
    color: "#000",
  },
  {
    id: 9,
    name: "Bootstrap",
    shortName: "BS",
    procent: 75,
    image: "../images/icons/bootstrap-icon.png",
    color: "#563d7c",
  },
  {
    id: 10,
    name: "Tailwind",
    shortName: "TW",
    procent: 55,
    image: "../images/icons/tailwind-icon.png",
    color: "#06b6d4",
  },
];
const myWorks = [
  {
    id: 1,
    name: "Sultan e-Market",
    url: "https://sultan-clone.netlify.app/",
    image: "../../../public/images/sultan.jpg",
    gurl: "https://github.com/AzizbekGitHub99/SultanOnlineMarket",
  },
  {
    id: 2,
    name: "CRUD - MOCK",
    url: "https://crudwithmock.netlify.app/",
    image: "../images/crud-mock",
    gurl: "https://github.com/AzizbekGitHub99/CRUDwithmock",
  },
  {
    id: 3,
    name: "Kuda Pizza",
    url: "https://kudapizzafromazyzbe.netlify.app/",
    image: "../images/crud-mock",
    gurl: "https://github.com/AzizbekGitHub99/kudapizza",
  },
  {
    id: 4,
    name: "Full ToDo App",
    url: "https://fulltodoapp.netlify.app/",
    image: "../images/crud-mock",
    gurl: "https://github.com/AzizbekGitHub99/fulltodoapp",
  },
  {
    id: 5,
    name: "Serveryanochka",
    url: "https://azyzbeexam.netlify.app/",
    image: "../images/crud-mock",
    gurl: "https://github.com/AzizbekGitHub99/Exam-4",
  },
  {
    id: 6,
    name: "Countries",
    url: "https://countriefromazyzbe.netlify.app/",
    image: "../images/crud-mock",
    gurl: "https://github.com/AzizbekGitHub99/Countries",
  },
  {
    id: 8,
    name: "Phone (Click Power on)",
    url: "https://phonefromazyzbe.netlify.app/",
    image: "../images/crud-mock",
    gurl: "https://github.com/AzizbekGitHub99/Phone",
  },
  {
    id: 9,
    name: "Pokemon",
    url: "https://pokemonsfromazyzbe.netlify.app/",
    image: "../images/crud-mock",
    gurl: "https://github.com/AzizbekGitHub99/pokemonfromazyzbe",
  },
  {
    id: 10,
    name: "Drag and Drop",
    url: "https://draganddropfromazizbe.netlify.app/",
    image: "../images/crud-mock",
    gurl: "https://github.com/AzizbekGitHub99/test-dnd",
  },
  {
    id: 11,
    name: "Weather App",
    url: "https://weatherappfromazizbe.netlify.app/",
    image: "../images/crud-mock",
    gurl: "https://github.com/AzizbekGitHub99/weather-app",
  },
  {
    id: 12,
    name: "Blog App",
    url: "http://azizbek-dev.uz/",
    image: "../images/crud-mock",
    gurl: "https://github.com/AzizbekGitHub99/blogwebsite",
  },
];

export { mySkills, myWorks };
